name: Publish release
on:
  push:
    tags:
      - "*"
      - "!*-BETA*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - name: Check version not snapshot
        run: |
          PROJECT_VERSION=$(./gradlew -q printVersion | tail -n 1)
          echo "Project version is $PROJECT_VERSION"
          if [[ "$PROJECT_VERSION" == *"SNAPSHOT" ]]; then exit 1; fi
      - name: Cache dependencies
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache wrapper
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Publish
        run: ./gradlew check publishPlugin -PdownloadIdeaSources=false -PintellijPublishToken="$INTELLIJ_PUBLISH_TOKEN"
        env:
          INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
      - name: Create Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
