name: Publish snapshot
on:
  push:
    tags:
      - "*-BETA*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - name: Check version is snapshot
        run: |
          PROJECT_VERSION=$(./gradlew -q printVersion | tail -n 1)
          echo "Project version is $PROJECT_VERSION"
          if [[ "$PROJECT_VERSION" != *"SNAPSHOT" ]]; then exit 1; fi
#      - name: Publish
#        run: ./gradlew check publishPlugin -PdownloadIdeaSources=false -PintellijPublishToken="$INTELLIJ_PUBLISH_TOKEN" -PintellijPublishChannels="beta"
#        env:
#          INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
      - name: changelog
        uses: ScottBrenner/generate-changelog-action@1.0.0
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Beta Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          prerelease: true
          draft: true
